### ISSUE TITLE
ssr/server.js errors

### ISSUE THREAD

**Issue by bdharris08** [grommet/grommet-todo#2]
On windows, If you 

```
node ssr/server.js
```

It will fail due to missing node-sass, react, babel-loader modules.
I submitted a pull request to add these, but withdrew it because if you then install those, you get something like the below error. I'm not sure how to fix that one - hence I closed the pull request.
Any ideas?

```
C:\grommet-todo\node_modules\enhanced-require\lib\execLoaders.js:195
        if(err) throw err;
                ^

Error: Loader throwed exeception: SyntaxError: : Unexpected token (13:6)
  11 |   render: function() {
  12 |     return (
> 13 |       <App centered={false}>
     |       ^
  14 |         <Header direction="row" justify="between"
  15 |           large={true} pad={{horizontal: 'medium'}}>
  16 |           <Title>Todo App</Title>
    at Parser.pp.raise (C:\grommet-todo\node_modules\babel-core\node_modules\babylon\lib\parser\location.js:24:13)
    at Parser.pp.unexpected (C:\grommet-todo\node_modules\babel-core\node_modules\babylon\lib\parser\util.js:91:8)
    at Parser.pp.parseExprAtom (C:\grommet-todo\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:514:12)
    at Parser.pp.parseExprSubscripts (C:\grommet-todo\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:267:19)
    at Parser.pp.parseMaybeUnary (C:\grommet-todo\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:247:19)
    at Parser.pp.parseExprOps (C:\grommet-todo\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:178:19)
    at Parser.pp.parseMaybeConditional (C:\grommet-todo\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:160:19)
    at Parser.pp.parseMaybeAssign (C:\grommet-todo\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:123:19)
    at Parser.pp.parseParenAndDistinguishExpression (C:\grommet-todo\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:566:26)
    at Parser.pp.parseExprAtom (C:\grommet-todo\node_modules\babel-core\node_modules\babylon\lib\parser\expression.js:471:19)
    at nextLoader (C:\grommet-todo\node_modules\enhanced-require\lib\execLoaders.js:173:15)
    at execLoaders (C:\grommet-todo\node_modules\enhanced-require\lib\execLoaders.js:44:14)
    at Function.module.exports.sync (C:\grommet-todo\node_modules\enhanced-require\lib\execLoaders.js:206:2)
    at RequireContext.theRequire (C:\grommet-todo\node_modules\enhanced-require\lib\RequireContext.js:167:17)
    at Object.<anonymous> (C:\grommet-todo\ssr\server.js:26:35)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

**Comment by DonalRafferty** [comment]
I am facing a similar issue to this, was this ever resolved?

For me the error I am getting after running the command gulp dev is:

> ERROR in ./src/js/index.js
> Module not found: Error: Cannot resolve module 'style' in C:\Users\raffertd\grommet-todo\src\js
>  @ ./src/js/index.js 5:0-29

**Comment by bdharris08** [comment]
I think my error was caused by chaining babel loaders in the wrong order. 
For your error, did you already try:
`npm install`
If so, it may be that they changed the path to the master style file for grommet and didn't update the todo example.

**Comment by DonalRafferty** [comment]
Sorry, I actually posted the error I get after installing the modules it says it failed to load, this is the message I get first:

> C:\Users\raffertd\Grommet\grommet-todo>gulp dev
> [15:47:40] Failed to load external module babel-regis
> [15:47:40] Failed to load external module babel-core/
> [15:47:40] Failed to load external module babel/regis
> C:\Users\raffertd\Grommet\grommet-todo\gulpfile.babel
> import yargs from 'yargs'
> ^^^^^^
> 
> SyntaxError: Unexpected reserved word

Surely this shouldn't be occurring after npm install!?

**Comment by bdharris08** [comment]
Yeah this appears to be an issue with your babel loaders.
"Import" is es6 syntax and you have to run the code through babel to transpile to a version of javascript that browsers can understand. 
At least, that's what it seems like is happening. 
So it looks like you are correct to `npm install`, but then you need to figure out the relative paths to the 'style' module.

**Comment by primozs** [comment]
It is missing babel-core babel-register and after you will install these it will be missing more stuff. but if you would use node >5, npm >3 then it would - should work without any additional installs because these modules are required in grommet-toolbox.

**Comment by alansouzati** [comment]
thanks @primozs. We updated our NPM version to be 3+ to avoid these sort of issues.

Please update your NPM, delete your node_modules, and run `npm install` again.

NPM 3+ all dependencies are flat inside node_modules, which brings a LOT of benefits, specially for windows users.
